from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime
import io

class GroundwaterReport:
    """Generates a formal PDF report for groundwater feasibility."""
    
    def __init__(self, query, risk_data, agent_response):
        self.query = query
        self.risk_data = risk_data # Dict with keys: district, risk_level, status
        self.agent_response = agent_response
        self.buffer = io.BytesIO()
        
    def generate(self):
        doc = SimpleDocTemplate(
            self.buffer, 
            pagesize=A4,
            rightMargin=72, leftMargin=72, 
            topMargin=72, bottomMargin=18
        )
        
        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#2c3e50"),
            alignment=1, # Center
            spaceAfter=30
        )
        
        header_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor("#2980b9"),
            spaceBefore=15,
            spaceAfter=10
        )
        
        normal_style = styles["Normal"]
        normal_style.fontSize = 11
        normal_style.leading = 16
        
        content = []
        
        # --- Title Page ---
        content.append(Paragraph("Jal-Rakshak: Groundwater Feasibility Report", title_style))
        content.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal_style))
        content.append(Spacer(1, 0.5*inch))
        
        # --- Inquiry Details ---
        content.append(Paragraph("1. Inquiry Details", header_style))
        content.append(Paragraph(f"<b>Query:</b> {self.query}", normal_style))
        content.append(Spacer(1, 0.2*inch))
        
        # --- Risk Assessment ---
        content.append(Paragraph("2. Risk Assessment Summary", header_style))
        
        # Risk Table
        risk_level = self.risk_data.get('risk_level', 'Unknown')
        risk_color = colors.green if "Safe" in risk_level else (colors.orange if "Critical" in risk_level else colors.red)
        
        data = [
            ["Parameter", "Assessment"],
            ["District/Block", self.risk_data.get("location", "Unknown")],
            ["Risk Category", risk_level],
            ["Groundwater Status", self.risk_data.get("status", "N/A")]
        ]
        
        t = Table(data, colWidths=[2*inch, 3*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (1,0), colors.HexColor("#ecf0f1")),
            ('TEXTCOLOR', (0,0), (1,0), colors.HexColor("#2c3e50")),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.white),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor("#bdc3c7")),
            # Highlight Risk Row
            ('TEXTCOLOR', (1,2), (1,2), risk_color),
            ('FONTNAME', (1,2), (1,2), 'Helvetica-Bold'),
        ]))
        content.append(t)
        content.append(Spacer(1, 0.3*inch))
        
        # --- Detailed Analysis ---
        content.append(Paragraph("3. AI Analysis & Recommendations", header_style))
        # Clean up markdown for PDF
        text = self.agent_response.replace("**", "").replace("#", "") 
        content.append(Paragraph(text, normal_style))
        content.append(Spacer(1, 0.5*inch))
        
        # --- Disclaimer ---
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=normal_style,
            fontSize=9,
            textColor=colors.gray,
            fontName='Helvetica-Oblique'
        )
        content.append(Paragraph("DISCLAIMER: This report is generated by an AI system based on available government data. Groundwater levels fluctuate seasonally. This document is for informational purposes only and does not constitute official legal advice. Please consult the local State Ground Water Data Centre before commencing any drilling activities.", disclaimer_style))
        
        doc.build(content)
        self.buffer.seek(0)
        return self.buffer.getvalue()  # Return bytes instead of BytesIO object

def create_pdf(query, location, risk_level, full_response):
    """Simple wrapper to create PDF bytes"""
    report = GroundwaterReport(
        query=query,
        risk_data={"location": location, "risk_level": risk_level, "status": "Based on CGWB Data"},
        agent_response=full_response
    )
    pdf_bytes = report.generate()
    return pdf_bytes
